platform :ios, '10.0'
inhibit_all_warnings!

target 'Example' do
  use_frameworks!
  
  pod 'Fable', :path => "../"
  pod 'AutoInch'
  pod 'Texture/Core'
  pod 'lottie-ios'
  pod 'Kingfisher'
  pod 'SnapKit'
  pod 'Then'
  pod 'SwiftMessages'
  pod 'SwifterSwift'
end
